[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
solc_version = "0.8.26"
evm_version = "paris"

remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "forge-std/=lib/forge-std/src/",
]

[profile.ci]
fuzz_runs = 1000

# Etherscan verification
[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }
